### ISSUE TITLE
Use Stories and Epics to Work More Efficiently

### ISSUE THREAD

**Issue by kchen0x** [kchen0x/reading#36]
this is a test comment2

**Comment by quentin-chen** [comment]
this is a test comment3

**Comment by quentin-chen** [comment]
这是我的一个注释。

> 这一段是引用的内容。

**Comment by quentin-chen** [comment]
undefined

**Comment by quentin-chen** [comment]
[object Object]

**Comment by quentin-chen** [comment]
这是评论

> 这是引用

**Comment by quentin-chen** [comment]
效果十分明显。

> You can work with bigger backlogs. You will organize the Stories in each Epic as a separate topic, without looking at the complete backlog.

**Comment by quentin-chen** [comment]
方法论部分

> You can use the subtasks in a Scrum planning process, or you can use them as an informal to-do list.

**Comment by quentin-chen** [comment]
方法论部分。

> Stories make your planning views smaller and easier to manage. They describe the important features that you want to release, and they hide extra details in subtasks.

**Comment by quentin-chen** [comment]
方便的笔记标注方案

> To add a subtask, open the parent Story ticket and view the Related Tickets tab. There, you can either relate an existing ticket as a subtask or Create a new related ticket to add a subtask to the Story.

**Comment by quentin-chen** [comment]
低成本的系统使用。

> The tasks are complete tickets, so you can assign them, discuss them, and see them in Cardwall and List views.

**Comment by quentin-chen** [comment]
格式的问题还需要继续调整。

> You can work with bigger backlogs. You will organize the Stories in each Epic as a separate topic, without looking at the complete backlog.

**Comment by quentin-chen** [comment]
统一的格式的好处在于可以非常方便的和其他系统转换。

> The Outline clearly shows your Epics in the left column. And, you can select the Epic type as part of a list filter.
