### ISSUE TITLE
你常用的这些服务原来还有那么多学生优惠

### ISSUE THREAD

**Issue by kchen0x** [kchen0x/reading#574]
<b>&#20320;&#24120;&#29992;&#30340;&#36825;&#20123;&#26381;&#21153;&#65292;&#21407;&#26469;&#36824;&#26377;&#37027;&#20040;&#22810;&#23398;&#29983;&#20248;&#24800;</b><br>
&#30446;&#24405; &#20026;&#20102;&#21560;&#24341;&#26032;&#23458;&#25143;&#12289;&#25552;&#39640;&#30041;&#23384;&#29575;&#65292;&#19981;&#23569;&#20844;&#21496;&#37117;&#20250;&#38024;&#23545;&#22312;&#26657;&#22823;&#23398;&#29983;&#32676;&#20307;&#25512;&#20986;&#30456;&#24212;&#30340;&#20248;&#24800;&#26041;&#26696;&#12290;&#22312;&#23569;&#25968;&#27966;&#31614;&#32422;&#20316;&#32773; @huhuhang &#20043;&#21069;&#30340;&#25991;&#31456; &#22312;&#26657;&#24072;&#29983;&#31119;&#21033;&#65306;Apple&#12289;&#24494;&#36719;&#12289;Adobe &#31561;&#20135;&#21697;&#22914;&#20309;&#36890;&#36807;&#25945;&#32946;&#20248;&#24800;&#36141;&#20080; &#20013;&#65292;&#24050;&#32463;&#20026;&#25105;&#20204;&#20171;&#32461;&#20102; Adobe&#12289;GitHub&#12289;JetBrains &#21644; Autodesk&hellip;<br>
<br>
March 7, 2018 at 10:09PM<br>
via Instapaper http://ift.tt/2G1skfY

**Comment by huhuhang** [comment]
哈哈哈哈，竟然被 @ 了。😂

**Comment by kchen0x** [comment]
因为用了相同的用户名。所以在提取摘要的时候就顺便被 @huhuhang 了，哈哈。
